---
profiles:
  default:
    network: Custom
    private_key: "0x78618406d49a1334e94a39394d0d5c11db6c6a29da55be54478b1b74bffc430b"
    public_key: "0xe7ae463d291a245c6186ad13d38cdf42e0b207d69968cbfed7c00afeebe5181e"
    account: ed56c3467b6bed0432a489e6f5adf9e9580b1bf3e3509694053149c42dc23020
    rest_url: "https://testnet.movementnetwork.xyz/v1"
    faucet_url: "https://faucet.testnet.movementnetwork.xyz/"
  mines_v12:
    network: Custom
    private_key: "0xf17a351a44abc767e81908339b89bdaef46f21e8cfa91cb70963d73c7156e841"
    public_key: "0xb59750d4ce30d76bc52dadd5577dbb1667c3be83b6c797be2a447325acca6782"
    account: 9cef2fdeac69283a0419d51fdf7ffd4430347c6aef63674282c8a3c97dbef204
    rest_url: "https://testnet.movementnetwork.xyz/v1"
    faucet_url: "https://faucet.testnet.movementnetwork.xyz/"
  mines_v12_fresh:
    network: Custom
    private_key: "0x6e8075089cadd826795f4973842836d9b1352a2a6f076f595676f35770ce5e47"
    public_key: "0xaab4113a9388c60920eae04ad1b7a6a0e659ac57c371f50c61db7adbc5641551"
    account: ca4cdf80ef00aa5582149f5797908abb0903727e22d53f26c3cffe7aaaadb47c
    rest_url: "https://testnet.movementnetwork.xyz/v1"
    faucet_url: "https://faucet.testnet.movementnetwork.xyz/"
  mines_v13:
    network: Custom
    private_key: "0x7c183b9f6494cecb460fb2bb1fa8b851fb6eeadd29eb9489a559eb312a52c2bc"
    public_key: "0x564859cd2e4428fa86e10c9a8ce48ebb1b7e8a4c7ed5174b7e3a6d20e7a33762"
    account: 0a9ee404e5582778c93a188b4ab011377073e3f72de6884b0d1a878c06488518
    rest_url: "https://testnet.movementnetwork.xyz/v1"
    faucet_url: "https://faucet.testnet.movementnetwork.xyz/"
