[package]
name = "Hello"
version = "1.0.0"

[addresses]
hello_addr = "0xd5002c5ac88d8db0e7bc8e047760c339d9ddd14ddb790e30a9b8ff7dc37c98be"

[dependencies]
AptosFramework = { local = "../move/local_framework/aptos-framework" }
