---
profiles:
  default:
    network: Custom
    private_key: "0x78618406d49a1334e94a39394d0d5c11db6c6a29da55be54478b1b74bffc430b"
    public_key: "0xe7ae463d291a245c6186ad13d38cdf42e0b207d69968cbfed7c00afeebe5181e"
    account: 0xed56c3467b6bed0432a489e6f5adf9e9580b1bf3e3509694053149c42dc23020
    rest_url: "https://testnet.movementnetwork.xyz/v1"
    faucet_url: "https://faucet.testnet.movementnetwork.xyz/"
