[package]
name = "TipJar"
version = "1.0.0"

[addresses]
tipjar_addr = "0x9cef2fdeac69283a0419d51fdf7ffd4430347c6aef63674282c8a3c97dbef204"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core"
rev = "ab80decffca5dd83991b5783073fe66ddde2836d"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/movementlabsxyz/aptos-core"
rev = "ab80decffca5dd83991b5783073fe66ddde2836d"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.MoveStdlib]
git = "https://github.com/movementlabsxyz/aptos-core"
rev = "ab80decffca5dd83991b5783073fe66ddde2836d"
subdir = "aptos-move/framework/move-stdlib"

