[package]
name = "MinesV12"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
mines = "0x0a9ee404e5582778c93a188b4ab011377073e3f72de6884b0d1a878c06488518"

[dependencies]
AptosFramework = { local = "../libs/aptos-core/aptos-move/framework/aptos-framework" }
